music_app/config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"

  resources :users, only: [:create, :new, :show]
  resource :session, only: [:new, :create, :destroy]

  resources :albums, except: [:index, :new]
  
  resources :bands do
    resources :albums, only: [:new]
  end

end

music_app/app/models/album.rb
# == Schema Information
#
# Table name: albums
#
#  id         :bigint           not null, primary key
#  title      :string           not null
#  year       :integer          not null
#  band_id    :bigint           not null
#  live?      :boolean          default(TRUE), not null
#  created_at :datetime         not null
#  updated_at :datetime         not null
#
class Album < ApplicationRecord
    validates :title, :year, :band_id, :live?, presence: true
    validates :band_id, uniqueness: { scope: :title }

    belongs_to :band,
        foreign_key: :band_id,
        class_name: :Band
end

music_app/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

music_app/app/models/band.rb
# == Schema Information
#
# Table name: bands
#
#  id         :bigint           not null, primary key
#  name       :string           not null
#  created_at :datetime         not null
#  updated_at :datetime         not null
#
class Band < ApplicationRecord
    validates :name, presence: true, uniqueness: true

    has_many :albums,
        foreign_key: :band_id,
        class_name: :Album

end

music_app/app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id              :bigint           not null, primary key
#  email           :string           not null
#  password_digest :string           not null
#  session_token   :string           not null
#  created_at      :datetime         not null
#  updated_at      :datetime         not null
#
class User < ApplicationRecord
    validates :email, :session_token, presence: true, uniqueness: true
    validates :password_digest, presence: true
    validates :password, length: {minimum: 6, allow_nil: true}

    before_validation :ensure_session_token

    attr_reader :password

    def self.find_by_credentials(email, password)
        @user = User.find_by(email: email)
        if @user && @user.is_password?(password)
            return @user
        else
            return nil
        end
    end

    def password=(password)
        @password = password
        self.password_digest = BCrypt::Password.create(password)
    end

    def is_password?(password)
        bcrypt_object = BCrypt::Password.new(self.password_digest)
        bcrypt_object.is_password?(password)
    end

    def reset_session_token!
        self.session_token = generate_unique_session_token
        self.save!
        self.session_token
    end

    def generate_unique_session_token
        token = SecureRandom::urlsafe_base64
        while User.exists?(session_token: token)
            token = SecureRandom::urlsafe_base64
        end
        token
    end

    def ensure_session_token
        self.session_token ||= generate_unique_session_token
    end

end

music_app/app/controllers/albums_controller.rb
class AlbumsController < ApplicationController
    #renders album
    def show
    end

    #render create new album page
    def new
        @album = Album.new
        @bands = Band.all
        @current_band_id = params[:band_id]
        render :new
    end
    
    #creates and saves into DB
    def create
        @album = Album.new(album_params)
        if @album
            redirect_to bands_url
        else
            render json: @album.errors.full_messages, status: 422
        end
    end

    #render update album page
    def edit
    end

    #updates and saves into DB
    def update
    end

    #deletes the album from DB
    def destroy
    end

    private
    def album_params
        params.require(:album).permit(:title, :band_id, :year, :live?)
    end
end

music_app/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

    helper_method :current_user, :logged_in?

    #crrlll
    
    #current_user to return the current user.
    def current_user
        @current_user ||= User.find_by(session_token: session[:session_token])
    end

    def require_logged_in
    end

    def require_logged_out
    end

    #logged_in? to return a boolean indicating whether anyone is signed in.
    def logged_in?
        !!current_user
    end

    #match session: session_tokens with current_user session_token
    #login!(user) reset the users session token and cookie
    def login!(user)
        session[:session_token] = user.reset_session_token!
    end

    #chainging session token for current user, and 
    def logout
        current_user.reset_session_token! if logged_in?
        session[:session_token] = nil
        @current_user = nil
    end
end

music_app/app/controllers/bands_controller.rb
class BandsController < ApplicationController
    before_action :set_band, only: [:show, :edit, :update, :destroy]

    #sets @band for those for methods
    def set_band
        @band = Band.find_by(id: params[:id])
    end

    #renders a page that shows all the bands
    def index
        @bands = Band.all
        render :index
    end
    
    #renders a create new band page
    def new
        @band = Band.new
        render :new
    end

    #creating band instance and saving to database
    def create
        @band = Band.new(band_params)
        if @band.save!
            redirect_to band_url(@band)
        else
            render json: @band.errors.full_messages, status: 422
        end
    end

    #render edit band info
    def edit
        # @band = Band.find_by(id: params[:id])
        render :edit
    end
    
    #edit band info
    def update
        # @band = Band.find_by(id: params[:id])
        if @band && @band.update(band_params)
            redirect_to band_url(@band.id)
        else 
            render json: @band.errors.full_messages, status: 422 #:unprocessable_entity
        end 
    end

    #show band page
    def show
        # @band = Band.find_by(id: params[:id])
        render :show
    end

    #delete a band
    def destroy
        # @band = Band.find_by(id: params[:id])
        @band.destroy
        redirect_to bands_url
    end

    private
    def band_params
        params.require(:band).permit(:name)
    end
end

music_app/app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

    #rendering log in page
    def new
        @user = User.new
        render :new
    end

    #logging in a user
    #reset user's session_token and session[:session_token], then redirect to UsersController#show
    def create
        incoming_email = params[:user][:email]
        incoming_password = params[:user][:password]
        @user = User.find_by_credentials(incoming_email, incoming_password)
        if @user
            login!(@user)
            redirect_to user_url(@user)
        else
            render :new
        end
    end

    #logging out a user and redirecting them to a login/sign up page
    def destroy
        logout
        redirect_to new_session_url
    end

end

music_app/app/controllers/users_controller.rb
class UsersController < ApplicationController
    #rendering sign up page
    def new 
        @user = User.new
        render :new
    end

    #creating a new user and saving it into the database
    #immediately after signing up, user's should log in and render the home page
    def create
        @user = User.new(user_params)
        if @user.save!
            login!(@user)
            redirect_to user_url(@user.id)
        else
            render json: @user.errors.full_messages, status: 422
        end
    end

    #rendering the user's page (displays the user's email)
    def show
        @user = User.find_by(id: params[:id])
        render :show
    end

    private 
    def user_params
        params.require(:user).permit(:email, :password, :password_digest, :session_token)
    end
end

music_app/app/helpers/albums_helper.rb
module AlbumsHelper
end

music_app/app/helpers/application_helper.rb
module ApplicationHelper
end

music_app/app/helpers/bands_helper.rb
module BandsHelper
end

music_app/app/helpers/users_helper.rb
module UsersHelper
end

music_app/app/views/albums/new.html.erb
<h1>Create a new album!</h1>

<form action="<%= albums_url %>" method="post">
    <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">

    <!-- drop down for selecting band -->
    <label for="band">Select a Band:</label>
    <select name="album[band_id]" id="band">
        <% @bands.each do |band| %>
            <% if band.id = @current_band_id %>
                <option value="<%= band.id %>" selected><%= band.name %></option>
            <% else %>
                <option value="<%= band.id %>"><%= band.name %></option>
            <% end %>
        <% end %>
    </select>
    
    <br>

    <!-- radio buttons to select album is live or studio -->
    <label for="live_or_studio"></label>
    Live<input type="radio" name="album[live?]" id="live_or_studio" value="true" >
    Studio <input type="radio" name="album[live?]" id="live_or_studio" value="false">

    

</form>

music_app/app/views/bands/edit.html.erb
<h1>Update <%= @band.name %>'s' info</h1>


<form action=" <%= band_url(@band) %>" method="post">
    <input type="hidden" name="authenticity_token" value="<%=form_authenticity_token%>">
    <input type="hidden" name="_method" value="patch">

    <label for="name">Band Name: </label>
    <input type="text" name="band[name]" id="name">

    <br>
    
    <input type="submit" value="Register Band">
</form>

music_app/app/views/bands/index.html.erb
<h1>List of all bands!</h1>
<a href="<%= new_band_url %>">Add a band</a>

<br><br><br>
<% @bands.each do |band| %>
    <a href="<%= band_url(band.id) %>"><%= band.name %></a>
    <br>
<% end %>

music_app/app/views/bands/new.html.erb
<h1>Create a new band</h1>

<form action=" <%= bands_url %>" method="post">
    <input type="hidden" name="authenticity_token" value="<%=form_authenticity_token%>">
    <label for="name">Band Name: </label>
    <input type="text" name="band[name]" id="name">

    <br>

    <input type="submit" value="Register Band">
</form>

music_app/app/views/bands/show.html.erb
<a href="<%= bands_url %>">See all bands</a>

<h1><%= @band.name %>'s Page</h1>

<a href=" <%= edit_band_url %>">Edit band info</a>

music_app/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MusicApp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "css_reset" %>
    <%= stylesheet_link_tag "application" %>
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Raleway:wght@900&family=Source+Sans+Pro:wght@300&display=swap" rel="stylesheet">
  </head>

  <body>
    <header>
      <h1>Music App</h1>
      <nav id="navbar">
        <ul>
          <li><a href="<%= bands_url %>">Bands</a><li>
          <li><% if logged_in? %>
          <form action="<%= session_url %>" method="post">
            <input type="hidden" name="_method" value="DELETE">
            <input type="submit" value="Logout">
          </form></li>
        </ul>
      <% end %>
      </nav>
    </header>
    
    <%= yield %>
  </body>
</html>

music_app/app/views/users/new.html.erb
<h1>Sign Up!</h1>

<form action="<%=users_url%>" method="POST">
<input type="hidden" name="authenticity_token" value="<%=form_authenticity_token%>">
    <label for="email">Email</label>
    <input type="text" id="email" name="user[email]">

    <br>

    <label for="password">Password</label>
    <input type="password" name="user[password]" id="password">

    <br>

    <input type="submit" value="Sign Up">
</form>

music_app/app/views/users/show.html.erb
<h1>user show page</h1>
<p>Email: <%= @user.email %></p>